class_name CharacterPresentationCatalog extends RefCounted

const Profile := preload(
	"res://presentation/characters/character_presentation_profile.gd")


static func active_profiles() -> Array:
	return [
		Profile.new(
			&"qiu_jue",
			&"char_kaiji_passive_v1",
			"🔥 {skill_name}　+2 番（点数 < 15000）",
			Color("ffb347"),
			true,
		),
		Profile.new(
			&"lin_yeche",
			&"char_akagi_passive_v1",
			"👁 {skill_name}　透视下家手牌",
			Color("8fb8ff"),
			true,
			"读脊",
		),
		Profile.new(
			&"bai_touli",
			&"char_washizu_passive_v1",
			"🔮 {skill_name}　看破三家各两张手牌",
			Color("d7b8ff"),
			true,
			"镜华",
		),
		Profile.new(
			&"an_cheng",
			&"char_awai_passive_v1",
			"🫧 {skill_name}　净化振听并预知下一摸",
			Color("9de8df"),
			true,
			"",
			"预知",
		),
		Profile.new(
			&"yuan_xi",
			&"char_koromo_passive_v1",
			"🌊 {skill_name}　末巡和牌 +3 番",
			Color("74cfe8"),
			true,
			"",
			"潮见",
			&"",
			"",
			Color("74cfe8"),
			{
				&"TILE_DRAWN": "",
				&"HAITEI": "🌊 {skill_name}　末巡和牌 +3 番",
				&"HOUTEI": "🌊 {skill_name}　末巡和牌 +3 番",
			},
			Vector2(420, 84),
		),
		Profile.new(
			&"hua_ling",
			&"char_saki_passive_v1",
			"✦ {skill_name}　+2 Dora",
			Color("7fe0c3"),
			true,
		),
		Profile.new(
			&"ying_li",
			&"char_momoko_passive_v1",
			"🌑 {skill_name}　潜伏解除 · +1 番",
			Color("b8add8"),
			true,
			"",
			"",
			&"primed",
			"消影一发 · 潜伏中",
			Color("a9a1c8"),
		),
		Profile.new(
			&"lian_yao",
			&"char_teru_passive_v1",
			"☀ {skill_name}　连斩加深",
			Color("ff7a45"),
			true,
			"",
			"",
			&"streak",
			"叠曜 {value} 层 · 本次 +{value} 番",
			Color("ff9a66"),
		),
		Profile.new(
			&"ju_jin",
			&"char_tetsuya_passive_v1",
			"◆ {skill_name}　+{han_delta} 番",
			Color("d9b65b"),
			true,
			"",
			"",
			&"wins",
			"阶升 {value} 阶 · 下次 +{next} 番",
			Color("d9b65b"),
			{},
			Vector2(110, 4),
			1,
		),
		Profile.new(
			&"bao_luo",
			&"char_kuro_passive_v1",
			"♦ {skill_name}　+2 赤 Dora",
			Color("ff5b6e"),
			true,
		),
	]
